const router = require("express").Router();
const deposito = require("./deposito");
const apertura = require("./apertura");
const historialCajero = require("./historialCajero");
const retiroCaja = require("./retiroCaja");
const remesas = require("./remesas");
const ticketsRemesas = require("./ticketsRemesas");
const kardex = require("./kardex");
const facturaAjusteInventario = require("./facturasAjusteInventario");
const existenciasTienda = require("./existenciasTiendas");
const cupones = require("./cupones");
const cajas = require("./cajas");
const usuario = require("./usuario");
const password = require("./password");
const inventario = require("./inventario");
const ajuste = require("./ajuste");
const devolucion = require("./devolucion");
const devolucionVenta = require("./devolucionVenta");
const venta = require("./venta");
const pedido = require("./pedido");
const pedidoProveedor = require("./pedidoProveedor");

router.use("/apertura", apertura);
router.use("/deposito", deposito);
router.use("/historialCajero", historialCajero);
router.use("/retiroCaja", retiroCaja);
router.use("/remesas", remesas);
router.use("/ticketsRemesas", ticketsRemesas);
router.use("/kardex", kardex);
router.use("/facturaAjusteInventario", facturaAjusteInventario);
router.use("/existenciasTienda", existenciasTienda);
router.use("/cupones", cupones);
router.use("/cajas", cajas);
router.use("/usuario", usuario);
router.use("/password", password);
router.use("/inventario", inventario);
router.use("/ajuste", ajuste);
router.use("/devolucion", devolucion);
router.use("/devolucionVenta", devolucionVenta);
router.use("/venta", venta);
router.use("/pedido", pedido);
router.use("/pedidoProveedor", pedidoProveedor);

module.exports = router;
