const router = require("express").Router();
const deposito = require("./deposito");
const apertura = require("./apertura");
const historialCajero = require("./historialCajero");
const retiroCaja = require("./retiroCaja");
const remesas = require("./remesas");
const ticketsRemesas = require("./ticketsRemesas");
const kardex = require("./kardex");
const facturaAjusteInventario = require("./facturasAjusteInventario");
const existenciasTienda = require("./existenciasTiendas");
const cupones = require("./cupones");
const cajas = require("./cajas");
const usuario = require("./usuario");
const password = require("./password");
const inventario = require("./inventario");
const ajuste = require("./ajuste");
const devolucion = require("./devolucion");
const devolucionVenta = require("./devolucionVenta");
const venta = require("./venta");
const pedido = require("./pedido");
const pedidoProveedor = require("./pedidoProveedor");

router.use("/Ajustes", ajuste);
router.use("/AperturasTiendas", apertura);
router.use("/Cajas", cajas);
router.use("/Cupones", cupones);
router.use("/Depositos", deposito);
router.use("/Devoluciones", devolucion);
router.use("/DevolucionesVentas", devolucionVenta);
router.use("/ExistenciasTiendas", existenciasTienda);
router.use("/FacturasAjustesInventarios", facturaAjusteInventario);
router.use("/HistorialesCajeros", historialCajero);
router.use("/Inventarios", inventario);
router.use("/Kardex", kardex);
router.use("/Passwords", password);
router.use("/Pedidos", pedido);
router.use("/PedidosProveedor", pedidoProveedor);
router.use("/Remesas", remesas);
router.use("/RetirosCaja", retiroCaja);
router.use("/TicketsRemesas", ticketsRemesas);
router.use("/Usuarios", usuario);
router.use("/Ventas", venta);

module.exports = router;
